[package]
name = "audio_analyzer_core"
version = "0.1.0"
edition = "2021"
authors = ["oligami <nziq53@gmail.com> (https://github.com/oligamiq)"]
license = "MIT/Apache-2.0"

[workspace]
members = ["audio_analyzer_app"]
default-members = ["audio_analyzer_app"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[workspace.dependencies]
audio_analyzer_core = { path = "." }
color-eyre = "0.6.3"

[dependencies]
cpal = { version = "0.15", features = ["wasm-bindgen"] }

# locad music file
symphonia = { version = "0.5.4", default-features = false, features = ["all-formats", "all-codecs", "mpa", "opt-simd", "all"] }

mel_spec = { git = "https://github.com/oligamiq/mel-spec" }

# debugging
color-eyre.workspace = true

# log
# utils
# directories = "5.0.1"
# predicates = "3.1.0"
# number_prefix = "0.4.0"
# crossbeam-channel = "0.5.13"

# low memory usage
# compact_str = "0.8.0"
parking_lot = "0.12.3"
# smallvec = "1.13.2"
ndarray = "0.16.1"
# hound = "3.5.1"

num-complex = "0.4.6"

# others
# https://ratatui.rs/recipes/apps/color-eyre/

log = { version = "0.4.22", features = ["std"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.95"
serde-wasm-bindgen = "0.6"
wasm-bindgen-futures = "0.4"
# to access the DOM (to hide the loading text)
web-sys = { version = "0.3.72", features = [
  "AudioContext",
  "MediaDevices",
  "MediaStreamConstraints",
  "MediaStream",
  "MediaStreamAudioSourceNode",
  "AudioWorklet",
  "AudioWorkletNode",
  "BaseAudioContext",
  "MessagePort",
  "MediaStreamAudioDestinationNode",
  "MessageEvent",
  "console",
  "Url",
  "BlobPropertyBag",
  "Blob"
  ] }
js-sys = { version = "0.3" }
# wasm_thread = "0.3.0"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
