[package]
name = "analyze-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
# audio io
cpal = "0.15.3"

# graphing and plotting
plotters = "0.3.6"

# command args
clap = { version = "4.5.7", features = ["derive", "unicode", "wrap_help"] }

# console
console = { version = "0.15.8", features = ["windows-console-colors"] }
ratatui = "0.26.3"
crossterm = "0.27.0"
indicatif = "0.17.8"
billboard = "0.2.0"
atty = "0.2.14"

# mel spectrogram
mel_spec = { git = "https://github.com/wavey-ai/mel-spec" }
mel_spec_pipeline = { git = "https://github.com/wavey-ai/mel-spec" }
mel_spec_audio = { git = "https://github.com/wavey-ai/mel-spec" }

# debugging
color-eyre = "0.6.3"

# log
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# utils
lazy_static = "1.4.0"
directories = "5.0.1"
predicates = "3.1.0"
number_prefix = "0.4.0"
crossbeam-channel = "0.5.13"

# low memory usage
compact_str = "0.7.1"
parking_lot = "0.12.3"
smallvec = "1.13.2"
ndarray = "0.15.6"

# others
# https://ratatui.rs/recipes/apps/color-eyre/
