[package]
name = "analyze-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
assert_no_alloc = "1.1.2"
cpal = "0.15.3"
crossterm = "0.27.0"
fundsp = "0.18.0"
plotters = "0.3.6"
plotters-backend = "0.3.6"
use = "0.0.1-pre.0"
