[package]
name = "filedl_on_web"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
js-sys = "0.3.76"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"

