[package]
name = "reqwest-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
anyhow = "1"
